[colors.primary]
foreground = "#ECE9EC"  # Bon Jour
background = "#111111"  # Cod Gray
dim_foreground = "#9aa2ad"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#111111"
cursor = "#ECE9EC"       # Royal Blue cursor

[colors.vi_mode_cursor]
text = "#111111"
cursor = "#db6c82"      # Brilliant Rose

[colors.search.matches]
foreground = "#ECE9EC"
background = "#554FE0"  # Royal Blue highlight

[colors.search.focused_match]
foreground = "#111111"
background = "#F9AB80"  # Apricot

[colors.hints.start]
foreground = "#ECE9EC"
background = "#db6c82"  # Brilliant Rose

[colors.hints.end]
foreground = "#FFFFFF"
background = "#554FE0"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#ECE9EC"
background = "#282c34"

[colors.selection]
text = "#111111"
background = "#db6c82"

[colors.normal]
black   = "#111111"  # Cod Gray
red     = "#db6c82"  # Brilliant Rose
green   = "#98c379"  # keep a natural green
yellow  = "#F9AB80"  # Apricot
blue    = "#554FE0"  # Royal Blue
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ECE9EC"  # Bon Jour

[colors.bright]
black   = "#5c6370"
red     = "#ff6fcf"
green   = "#a8d37a"
yellow  = "#ffd399"
blue    = "#7b77ff"
magenta = "#dd8cff"
cyan    = "#6be0ff"
white   = "#FFFFFF"

[colors.dim]
black   = "#21252b"
red     = "#d1509e"
green   = "#7da869"
yellow  = "#d19a66"
blue    = "#3f3abf"
magenta = "#a678dd"
cyan    = "#4aa5b7"
white   = "#9aa2ad"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
size = 12.0
